### ISSUE TITLE
How to determine whenever there's an oscilaltion in data using GPosc?

### ISSUE THREAD

**Issue by TorkelE** [ManchesterBioinference/GPosc#1]
Hello,

I have some data from single-cell experiments which I wish to classify whenever there is an oscillation or not:
![image](https://user-images.githubusercontent.com/18099310/144028057-8100a754-ea86-4e69-9445-2d2cee9fc201.png)
![image](https://user-images.githubusercontent.com/18099310/144028138-263b0490-697a-4e9b-8e85-9f42c14f89d5.png)
![image](https://user-images.githubusercontent.com/18099310/144028209-c31c1098-83a0-4014-b98e-0dc2fabdde00.png)
(these are just some examples, it ranges from stuff which are just single pulses, something which probably is an oscillation, and then stuff which gets less oscillatory)

Unfortunately, I have been unable to find any documentation on how to use your tool to do this for data. All the documentation included in the repository is just for the "Gaussian Processes for Machine Learning" package, and nothing for determining oscillations. In addition, the instructions for how to install the package is not extensive, which made me a bit uncertain, do I need all the files in the repository?

How would you recommend that I go about for this? Is there a single function that I could use? Or is there an example with the methodology which you would recommend that I follow? Also, exactly which files would I need to download?

**Comment by Nick-E-P** [comment]
Dear Torkel,

I apologise if it's not clear how to run the analysis. In fact, while
finishing the paper I was transitioning to a new job, and I agree the
documentation is insufficient.

Last year I helped someone analyse some single cell data and I rewrote some
of the functions in Python. If it's okay with you, we can find out what
you'd like to do and then I'll try and add a Jupyter notebook with the
required analysis steps (which should hopefully be clearer).

First of all, the data looks pretty cool, but the second plot makes me
nervous. GPosc is mainly designed for discriminating between noisy
fluctuations vs noisy oscillations. The data in the second plot looks more
like excitable dynamics, with three large, dominant pulses on top of a low
background level. In fact it reminds me of the p53 data shown in this paper
(Figure 1) https://www.nature.com/articles/srep46571 . The method they used
involves a wavelet transformation and then peak finding. The first author
of the paper has released a package for wavelet analysis
https://www.biorxiv.org/content/10.1101/2020.04.29.067744v3.abstract (and
there's another related pre-print for circadian dynamics
https://arxiv.org/pdf/2107.14066.pdf ). That methodology might be more
appropriate for excitable dynamics because the dynamics of your second plot
(i.e. large, occasional pulses) are probably not well-modelled by GPosc.

That being said, we can give GPosc a try. In the original paper, we
performed imaging of four blank regions of the plate (with no cells) in
order to estimate the amount of measurement noise. Do you have similar
data? If not, I can make a modification to the script that will also try
and estimate measurement noise for each cell.

I've also used the approach to instead infer difference in frequency across
two different populations (see example graph). Are you interested in
differences in dynamics (e.g. period and oscillation quality) between two
populations? In general, I feel that the analysis pipeline for detecting
differences in dynamics between two different populations of cells is
normally more robust than asking for the number of oscillating cells in a
single population
[Step 3 parameter inference.pdf](https://github.com/ManchesterBioinference/GPosc/files/7625741/Step.3.parameter.inference.pdf)
.

**Comment by TorkelE** [comment]
Dear Nick,

I think you are straight on point. The system is most likely excitable. Basically, what we got is a system that responds to an input. For a small input, it only displays the random pulses. As the input grows larger the pulses eventually get more regular, eventually turning into an oscillation. For a strong input, it just stays on all the time. We wanted to see if we could have a test that confirms that it eventually goes into an oscillation (and eventually stops oscillating, and just stays on and fluctuates it).

Your reply is really helpful! You are probably right that the wavelet base analysis is better, as we indeed deal with the pulses for the weaker input. But maybe you are right that just trying to determine pulse frequency across the various inputs strengths is the better way to go. Your link does only seem to point towards a figure without a caption, maybe it is the wrong one?

again, many thanks!

**Comment by Nick-E-P** [comment]
Dear Torkel,

Just to clarify the figure I sent: we had a gene that shows noisy oscillations and a mutated version. We fitted one of the models from the PLOS Comp Bio paper (specifically the OUosc model) to all cells, and you can see on the plot that the frequency of oscillations is shifted in the two populations. As you suggest, it might be nice to create a similar graph for your data at multiple different inputs strengths.

I'm a bit blocked this week until Friday afternoon, but I'll try and create a little notebook ASAP and get back to you when it's done!

Best,
Nick

**Comment by TorkelE** [comment]
Thank you!
A notebook would be really cool, but don't feel any hurry about it!
Kind regards,
Torkel

**Comment by Nick-E-P** [comment]
Dear Torkel,

I apologise for the incredibly long delay!

I've now created a Jupyter Notebook tutorial to describe the steps of GPosc for finding oscillations, which can be found in /GitHub/GPosc/Python/tutorial.ipynb

You can also view this tutorial with this link: https://nbviewer.org/github/ManchesterBioinference/GPosc/blob/master/Python/tutorial.ipynb

The data required for running the tutorial is in GitHub/GPosc/Python/Data.

I've also put a script to reproduce the main paper results in  /GPosc/Python/PaperResultsFig8.py

Please let me know if you have any further issues or questions.

Best,
Nick

**Comment by TorkelE** [comment]
thanks for having a look at this again. This might turn up useful when I get back to this problem, at which point I will have a look at it!
